# Site settings
title: Darli's Uncle
email: "jellygameadscene@gmail.com"
description: "疯狂程序员的博客"
baseurl: ""
url: "http://deardarli.cn"
permalink: /:year/:title


# Social account
twitter:  darlisuncle
weibo:    850176300@qq.com
github:   850176300
codepen:  P233
dribbble: jellygame


# Comment
disqus_shortname: deardarli.cn


# Google Analytics
google_analytics: UA-96108977-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
